model:
  name: sam2
  checkpoint: "facebook/sam2-vit-h" # または "facebook/sam2-vit-l"や"facebook/sam2-vit-b"
  freeze_image_encoder: false

training:
  batch_size: 4
  epochs: 10
  lr: 1.0e-5
  weight_decay: 0.01
  num_workers: 4
  seed: 42
  save_interval: 1
  eval_interval: 1
  gradient_accumulation_steps: 2
  mixed_precision: "fp16"

data:
  train_image_dir: "data/images/train"
  train_mask_dir: "data/masks/train"
  val_image_dir: "data/images/val"
  val_mask_dir: "data/masks/val"
  annotations_file: "data/annotations.json"
  image_size: 1024
  num_points_per_mask: 10
  max_masks_per_image: 20

logging:
  use_wandb: true
  project_name: "sam2_manga_finetune"
  run_name: "sam2_manga_finetune"